### ISSUE TITLE
Phillps LightAide

### ISSUE THREAD

**Issue by MGlaab** [Gricha/neotrellis#1]
This is more of a request not an issue. This is a great project; getting kids involved with electronics and making "toys" is great. Your project reminds me of a product that used to be available to children who were visually impaired. Phillps made it and has since stopped making it. 

https://www.wonderbaby.org/articles/lightaide-funding 

I have tried to create a LightAide for my niece who is visually impaired. I've created the hardware and written some one-off programs using Arduino, but I can't seem to figure out the logic for the whole unit to function.
I'll be looking at your code to try to understand the logic because it seems you've gotten things to work in that regard.
Anyways, thanks for posting your project. It might help me figure my project out.

**Comment by gricha** [comment]
Hey! Thank you for posting this. What type of hardware did you set up for this?

For context the project here uses 4x4 Trellis boards from adafruit:
https://www.adafruit.com/product/3954 with silicon elastometers: https://www.adafruit.com/product/1611
This is to say that the project is just really easy on the front of connecting hardware, since Adafruit just has a specific guidelines and libraries (seesaw) to support connecting them like lego bricks.

**Comment by MGlaab** [comment]
My hardware consists of a single line of 240 neopixels arranged in a 12x20 grid/matrix. I also have used Adafruit libraries(Neopixel, GFX, NeoMatrix) as well as FastLED. The GFX library is great to use if you just want to display a sequence of patterns/shapes/lines but getting user input while this was happening created problems. Then I tried to learn state machines and that's where I got stuck. Then I read a lot about game design, then I wrote some code in python and the hardware was a raspberry pi. The project has turned into more of a learning experience, though I would like my niece to use it in a finished form someday.

**Comment by gricha** [comment]
Ah I gotcha! I had to do the model in which I have ability to read out input between each loop refresh here: https://github.com/Gricha/neotrellis/blob/main/src/core/engine.cpp#L165-L172

The trickery with that is that taking input (from Trellis specifically) is a bit costly, so doing it every loop ended up being no-go for some activities, but in general to start you can have input reads between each loop.

My code is a bit over-engineered for what it's doing and it's using C++, but I'm happy to provide clarifications for it. Also if you have particular code snippet with specific expected behavior, I'm happy to give you some pointers, although cannot promise anything (as you can see by my slow response times 😬 )
